name: Create Release version in a project
description: JIRA integration with Github Actions to create a release version in a project
inputs:
  jira-username:  # id of input
    description: 'JIRA username for authentication'
    required: true
  jira-api-token:
    description: 'JIRA API token for authentication'
    required: true
  jira-project-id: 
    description: 'JIRA Project ID'
    required: true
  atlassian-domain:
    description: 'Atlassian JIRA domain URI'
    required: true
  latest-git-tag:
    description: 'Latest git tag in the repo'
    required: true
  which-release:
    description: 'Either current release or next release to be checked for'
    required: true 
runs:
  using: node12 
  main: 'dist/index.js'